Name = input("Enter your Name :")
Surname = input("Enter your Surname :")
a = float (input("Enter Foundation English "))
b = float (input("Enter General Business "))
c = float (input("Enter Introduction to Computer Systems "))
d = float (input("Enter Computer Programming "))
print (Name,Surname)
print ("You Score is")
print ("Foundation English :",a)
print ("General Business :",b)
print ("Introduction to Computer Systems :",c)
print ("Computer Programming :",d)
